version: '3.8'

services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - nodenet
    ports:
      - "3002:3000"
    entrypoint: wait-for db:3306 -t 10 -- ./start.sh
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: mydatabase
    depends_on:
      - db
    command: node app.js

  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "8087:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - node-app

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    # restart: always
    tty: true
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - nodenet
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: rootpassword
    # ports:
    #   - "3307:3306"
networks:
  nodenet:
    driver: bridge
